const PREFIX = 'JILLIST_MODALS/';

export const SET_MODAL_VISIBILITY = PREFIX + 'SET_MODAL_VISIBILITY';
export const SET_MODAL_DATA = PREFIX + 'SET_MODAL_DATA';
export const SET_MODAL_ERRORS = PREFIX + 'SET_MODAL_ERRORS';
export const RESET_MODAL_DATA = PREFIX + 'RESET_MODAL_DATA';
