language: python
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database jillist;' -U postgres
  - psql -c 'create database test_jillist;' -U postgres
  - python manage.py db upgrade
install:
  - "pip install -r requirements.txt"
script: python manage.py tests
