const PREFIX = 'JILLIST_RESOURCE/';

export const SET_ITEMS = PREFIX + 'SET_ITEMS';
export const SET_ITEM = PREFIX + 'SET_ITEM';
export const UPDATE_ITEM = PREFIX + 'UPDATE_ITEM';
export const SET_DELETE_ITEM = PREFIX + 'SET_DELETE_ITEM';
export const CLEAR_DELETE_ITEM = PREFIX + 'CLEAR_DELETE_ITEM';
export const DELETE_ITEM = PREFIX + 'DELETE_ITEM';