"""details

Revision ID: 57836204f1d5
Revises: b9831a65e8a6
Create Date: 2017-06-15 20:18:57.559025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57836204f1d5'
down_revision = 'b9831a65e8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'details')
    # ### end Alembic commands ###
