"""waiting on

Revision ID: eda5f95e03d0
Revises: 57836204f1d5
Create Date: 2017-07-22 11:33:47.449165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda5f95e03d0'
down_revision = '57836204f1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('waiting_on', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'waiting_on')
    # ### end Alembic commands ###
