const PREFIX = 'JILLIST_NOTIFICATIONS/';

export const REMOVE_NOTIFICATION = PREFIX + 'REMOVE_NOTIFICATION';
export const ADD_NOTIFICATION = PREFIX + 'ADD_NOTIFICATION';
export const SET_NOTIFICATION_REMOVED = PREFIX + 'SET_NOTIFICATION_REMOVED';
